name: Update subscriptions

on:
  schedule:
    - cron: '*/65 * * * *'
  workflow_dispatch:

jobs:
  update-subscriptions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
