name: Update subscriptions

on:
  schedule:
    - cron: '*/65 * * * *'
  workflow_dispatch:

jobs:
  update-subscriptions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install and run script
        run: |
          cd working && npm install axios atob btoa
          node app.js

      - name: Move files to directories
        run: |
          mkdir -p full
          mv working/5ubscrpt10n.txt full/
          mv working/5ubscrpt10n_b64.txt full/
          mkdir -p protocols
          mv working/vmess.txt protocols/
          mv working/vless.txt protocols/
          mv working/shadowsocks.txt protocols/
          mv working/trojan.txt protocols/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes to repository
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Update subscriptions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
